{"uuid": "f0ab1549-ee84-40ea-8fb2-9a8f66270c23", "children": ["b9fb3607-ed49-4f4d-a9a1-a2eb467d86ca"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\n\n", "trace": "  File \"C:\\Users\\Microsoft\\AppData\\Roaming\\Python\\Python39\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\program files\\python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\program files\\python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Workspaces\\Selenium\\Selenium-Tutorial\\Tests\\conftest.py\", line 9, in test_setup\n    driver.implicitly_wait(5)\n  File \"C:\\Users\\Microsoft\\AppData\\Roaming\\Python\\Python39\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 911, in implicitly_wait\n    self.execute(Command.SET_TIMEOUTS, {\n  File \"C:\\Users\\Microsoft\\AppData\\Roaming\\Python\\Python39\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Microsoft\\AppData\\Roaming\\Python\\Python39\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1627754239745, "stop": 1627754241829}], "start": 1627754239745, "stop": 1627754242183}